// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Hero;

/************************************************************/
/**
 * 
 */
public class Assasin extends Hero {

	public Assasin() {
		super("Assasin",50,50);
	}
		
};
