// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

/************************************************************/
/**
 * 
 */
public abstract class Charcs {
	/**
	 * 
	 */
	protected int attackvalue;
	/**
	 * 
	 */
	protected int hppool;
	
	

	protected int maxhppool;

	/**
	 * 
	 */
	
	// a.attacks(b);
	// b.isAttackedBy(a);
	public void Attack(Charcs victim) {	
		victim.isAttackedBy(this.attackvalue);
	}
	
	public int getHppool() {
		return hppool;
	}

	public void setHppool(int hppool) {
		this.hppool = hppool;
	}

	public int getAttackvalue() {
		return attackvalue;
	}

	public void setAttackvalue(int attackvalue) {
		this.attackvalue = attackvalue;
	}

	public int getMaxhppool() {
		return maxhppool;
	}

	public void setMaxhppool(int maxhppool) {
		this.maxhppool = maxhppool;
	}
	public void isAttackedBy(int attackv) {
		//
		this.hppool = this.hppool - attackv;
		if(this.hppool<0) {this.setHppool(0);}  // if health less than zero set it to zero
	}

	@Override
	public String toString() {
		return "attackvalue=" + attackvalue + ", hppool=" + hppool + ", maxhppool=" + maxhppool;
	}
	
	/**
	 * 
	 */
	
};
