// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Hero;

/************************************************************/
/**
 * 
 */
public class Cleric extends Hero {

	public Cleric() {
		super("Shaman",35,50);
		// TODO Auto-generated constructor stub
	}
	
};
