// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import java.util.ArrayList;

public class Fight {
	
	
	private Monster[] monsters;
	private Hero[] heros;
	private int number;
	private int level;
	private int turn;
	
	
	
	public void choosemonsters() {
		// int ran;
		this.monsters = new Monster [3];
//		for (int i=0; i < this.number-this.level+1 ; i++) {
//			ran =  (int) (1+ Math.random()*3);
//			switch (ran) {
//				case 1: this.monsters[i] = new Spider();
//				case 2: this.monsters[i] = new Slime();
//				case 3: this.monsters[i] = new Spider();
//			}
//			for (i=0; i < this.level-1 ; i++) {
//				ran =  (int) (1+ Math.random()*1);
//				switch (ran) {
//					case 1: this.monsters[i] = new Mummy();
//				}
//			
//			}
//		}
		this.monsters[0] = new Spider();
		this.monsters[1] = new Slime();
		this.monsters[2] = new Mummy();
	}

	public Fight(Hero[] heros, int number, int level) {
		super();
		this.heros = heros;
		this.number = number;
		this.level = level;
		this.turn = 1;  //Heors Start first always
		this.choosemonsters();	 
	}
	
	public boolean judge() {
		int gcheck, pcheck;
		gcheck = 0;
		for (Hero h:this.heros) {
			if (h.hppool < 1) {
				gcheck += 1;
			}
		}
		if (gcheck == 4) {
			System.out.println("Game Over!");
			return false;
		}
		pcheck = 0;
		for (Monster m:this.monsters) {
			if (m.hppool < 1) {
				pcheck += 1;
			}
		}
		if (pcheck == this.monsters.length) {
			System.out.println("All monsters Dead. You can Proceed to The Next Round!");
			return false;
		}	
		return true;
	}
	
	
	public void StartRound() {
		while(this.judge()) {
			
			if(turn==1) {System.out.println("The Heros - ");
			System.out.println("--------------------------------------");
			
			for (Hero i : this.heros) {System.out.println(i.name + " "+ i.getHppool() +"/" +i.getMaxhppool());}
			
			System.out.println("--------------------------------------");
			
			System.out.println("The Monsters - ");
			System.out.println("--------------------------------------");
			for (Monster i : this.monsters) {
				System.out.println(i.name + " "+ i.getHppool()+"/" +i.getMaxhppool());
			}
			System.out.println("--------------------------------------");}
			
			
			Round round = new Round(this.heros,this.monsters,this.turn);
			
			round.action();
			this.heros = round.getHeros();
			this.monsters = round.getMonsters();
			this.turn = this.turn*(-1);

			
	}
	}
	
};
