// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Charcs;

/************************************************************/
/**
 * 
 */
public class Hero extends Charcs {
	/**
	 * 
	 */
	protected String name;

	public Hero(String name, int attackv,int hpp) {
		super();
		this.name = name;
		this.hppool = hpp;
		this.maxhppool = hpp;
		this.attackvalue = attackv;
	}
	public String toString() {
		return "name\t"+name+"attackvalue=" + attackvalue + ", hppool=" + hppool + ", maxhppool=" + maxhppool;
	}	
	


	
	
};
