// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Charcs;

/************************************************************/
/**
 * 
 */
public class Monster extends Charcs {
	
	protected String name;

	public Monster(String name, int attackv,int hpp) {
		super();
		// TODO Auto-generated constructor stub
		this.name = name;
		this.hppool = hpp;
		this.maxhppool = hpp;
		this.attackvalue = attackv;
	}
	
	
};
