// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Monster;

/************************************************************/
/**
 * 
 */
public class Mummy extends Monster {

	public Mummy() {
		super("Mummy",50, 75);
		// TODO Auto-generated constructor stub
	}
	
};
