// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Hero;

/************************************************************/
/**
 * 
 */
public class Paladin extends Hero {

	public Paladin() {
<<<<<<< HEAD
		super("Aladin",20,95);
=======
		super("Paladin",20,95);
>>>>>>> branch 'master' of https://github.com/hamiddhosseini/MAEGAME.git
		// TODO Auto-generated constructor stub
	}
};
