// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import java.util.Scanner;

/************************************************************/
/**
 * 
 */
public class Round {
	Hero [] heros;
	Monster [] monsters;
	int turn;
	public Round(Hero[] heros, Monster[] monsters, int turn) {
		super();
		this.heros = heros;
		this.monsters = monsters;
		this.turn = turn;
	}
	
	public void action() {	
		if(this.turn==1) {
			this.herosattack();
		}
		else {
			this.monstersattack();
		}
	}

	public void herosattack() {
		
		System.out.println("Heros are Attacking!");
		
		//randomly select hero to attack
		int ran;
		while(true) {
<<<<<<< HEAD
		ran =  (int) (4*Math.random());
		if(this.heros[ran].getHppool()>0) {break;}
		}
		
		
		//user selects which monster to attack
		System.out.println("Who will " + this.heros[ran].name + " attack"  );
		
//		for(Monster i:this.monsters) {
//			System.out.println(i.name + "  -   " + i.getHppool());
//		}
		
		Scanner sc = new Scanner(System.in);
		int x = sc.nextInt();

		this.heros[ran].Attack(this.monsters[x-1]);
		
=======
			ran =  (int) (4*Math.random());
			if(this.heros[ran].getHppool()>0) {break;}
		}
		
		this.heros[ran].chooseVictim(this.monsters,this.heros);
				
>>>>>>> branch 'master' of https://github.com/hamiddhosseini/MAEGAME.git
	}
	
	public void monstersattack() {
		System.out.println("Monsters are Attacking!");
		//randomly select which monster attacks
		int ran;
		while(true) {
			ran =  (int) (3*Math.random());
			if(this.monsters[ran].getHppool()>0) {break;}
			}
		
		//randomly select hero to attack to 
		int x;
		while(true) {
			x =  (int) (4*Math.random());
			if(this.heros[x].getHppool()>0) {break;}
			}
		
		this.monsters[ran].Attack(this.heros[x]);
		
		System.out.println( this.monsters[ran].name + " attacked " + this.heros[x].name);
	}
	
	
	public Hero[] getHeros() {
		return heros;
	}
	public Monster[] getMonsters() {
		return monsters;
	}

	
};
