// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Monster;

/************************************************************/
/**
 * 
 */
public class Slime extends Monster {
	public Slime() {
		super("Slime",20, 50);
		// TODO Auto-generated constructor stub
	}
	
};
