// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Monster;

/************************************************************/
/**
 * 
 */
public class Spider extends Monster {
	public Spider() {
		super("Spider",20, 50);
		// TODO Auto-generated constructor stub
	}
	
};
