// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Game;

/************************************************************/
/**
 * 
 */
public class TestClass {
	/**
	 * 
	 */
	public static Game game;
	public static void main(String [] args) {
		game = new Game();
		game.startgame();

		System.out.println(game.heros);

//		int ran;
//		int i;
//		for(i = 0; i<10;i++) {
//		ran =  (int) (4*Math.random());
//		System.out.println(ran);
//		}
		
	}

};
