// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Hero;

/************************************************************/
/**
 * 
 */
public class Warrior extends Hero {

	public Warrior() {
		super("Warrior",35,85);
		// TODO Auto-generated constructor stub
	}
};
