// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGAME;

import MAEGAME.Hero;

/************************************************************/
/**
 * 
 */
public class Warrior extends Hero {

	public Warrior() {
<<<<<<< HEAD
		super("Goku",35,85);
=======
		super("Warrior",35,85);
>>>>>>> branch 'master' of https://github.com/hamiddhosseini/MAEGAME.git
		// TODO Auto-generated constructor stub
	}
};
